version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-maintenance-system
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
 
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maintenance-system-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mongo-data: